new_tab dev-servers
layout grid
launch --location=split --title="Frontend" bash -c "cd ~/Documents/OtherProjects/expenses_tracker/frontend/expenses-tracker && npm run dev; exec bash"
launch --location=split --title="Backend" bash -c "cd ~/Documents/OtherProjects/expenses_tracker/backend/ExpensesApi && dotnet run; exec bash"
