# Cursors
env = HYPRCURSOR_THEME,phinger-cursors-dark
env = HYPRCURSOR_SIZE,24

# QT Theme
env = QT_QPA_PLATFORMTHEME,gtk3

# Portal/Desktop
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
