# Waybar, Mako and Wallpaper
exec-once = waybar
exec-once = mako
exec-once = awww-daemon & sleep 0.5 && awww img  ~/dotfiles/wallpapers/current.png

# Polkit agent (hyprpolkitagent)
exec-once = systemctl --user start hyprpolkitagent

# Cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# D-Bus activation
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Disable auto focus webcam
exec-once = v4l2-ctl -d /dev/video0 --set-ctrl=focus_automatic_continuous=0

# EasyEffects audio effects
exec-once = easyeffects --service-mode
