$base           = 0xff1e1e2e
$surface        = 0xff181825
$overlay        = 0xff313244
$muted          = 0xff6c7086
$subtle         = 0xffa6adc8
$text           = 0xffcdd6f4
$red            = 0xfff38ba8
$yellow         = 0xfff9e2af
$blue           = 0xff89b4fa
$pink           = 0xfff5c2e7
$teal           = 0xff94e2d5
$cyan           = 0xff89dceb
$purple         = 0xffcba6f7
$highlightLow   = 0xff313244
$highlightMed   = 0xff45475a
$highlightHigh  = 0xff585b70

$background = $base
$accent = $blue

