### IMPORTS ###

# Colors
source = ./colors.conf

# Base configs
source = ./hyprland/*.conf

render:cm_sdr_eotf = 3
target-colorpsace-hint=no
monitorv2 = DP-1, sdr_eotf, srgb
monitorv2 = DP-2, sdr_eotf, srgb
monitorv2 = DP-3, sdr_eotf, srgb

source = /home/kasper/.config/hypr/noctalia/noctalia-colors.conf

