### IMPORTS ###

# Colors
source = ./colors.conf

# Base configs

source = ./hyprland/*.conf

# Profile overrides

source = ./overrides/*.conf

render:cm_sdr_eotf = 3
target-colorpsace-hint=no
monitorv2 = DP-1, sdr_eotf, srgb
monitorv2 = DP-2, sdr_eotf, srgb
monitorv2 = DP-3, sdr_eotf, srgb
