$base           = 0xff1e1e2e
$surface        = 0xff585b70
$overlay        = 0xff585b70
$muted          = 0xff7f849c
$subtle         = 0xff7f849c
$text           = 0xffcdd6f4

$red            = 0xfff5c2e7
$yellow         = 0xffa6e3a1
$blue           = 0xfff9e2af
$pink           = 0xfff5c2e7
$teal           = 0xff89b4fa
$cyan           = 0xff94e2d5
$purple         = 0xfff38ba8

$highlightLow   = 0xff585b70
$highlightMed   = 0xff7f849c
$highlightHigh  = 0xffa6adc8

$background = $base
$accent     = 0xff89b4fa

# Base configs
source = ./hyprland/*.conf

render:cm_sdr_eotf = 3
target-colorpsace-hint=no
monitorv2 = DP-1, sdr_eotf, srgb
monitorv2 = DP-2, sdr_eotf, srgb
monitorv2 = DP-3, sdr_eotf, srgb

source = /home/kasper/.config/hypr/noctalia/noctalia-colors.conf

