$primary = rgb(37f499)
$surface = rgb(212337)
$secondary = rgb(04d1f9)
$error = rgb(f16c75)
$tertiary = rgb(a48cf2)
$surface_lowest = rgb(222539)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
